# Generated by Django 3.1 on 2020-08-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='Email',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
