# Generated by Django 3.1 on 2020-08-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_remove_member_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Region',
            field=models.CharField(blank=True, choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], max_length=10),
        ),
    ]
